/**
 * Creating an sidebars object
 */
function generateSidebars() {
  return {
    tutorialSidebar: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
    ],
    // Custom sidebar for the textbook
    textbookSidebar: [
      {
        type: 'category',
        label: 'Physical AI & Humanoid Robotics Textbook',
        items: [
          'intro',
          {
            type: 'category',
            label: 'Module 1: The Robotic Nervous System (ROS 2)',
            link: {
              type: 'generated-index',
              description: 'Weeks 1-5: Foundations of Physical AI, ROS 2 Architecture, rclpy, URDF/Xacro, and Launch Systems'
            },
            items: [
              'module-1-robotic-nervous-system/week-1',
              'module-1-robotic-nervous-system/week-2',
              'module-1-robotic-nervous-system/week-3',
              'module-1-robotic-nervous-system/week-4',
              'module-1-robotic-nervous-system/week-5'
            ],
          },
          {
            type: 'category',
            label: 'Module 2: The Digital Twin (Gazebo & Unity)',
            link: {
              type: 'generated-index',
              description: 'Weeks 6-7: Digital twins, simulation environments, Gazebo and Unity integration with ROS 2'
            },
            items: [
              'module-2-digital-twin/week-6',
              'module-2-digital-twin/week-7'
            ],
          },
          {
            type: 'category',
            label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™ Platform)',
            link: {
              type: 'generated-index',
              description: 'Weeks 8-10: NVIDIA Isaac platform, stereo visual SLAM, navigation and manipulation frameworks'
            },
            items: [
              'module-3-isaac-brain/week-8',
              'module-3-isaac-brain/week-9',
              'module-3-isaac-brain/week-10'
            ],
          },
          {
            type: 'category',
            label: 'Module 4: Vision-Language-Action Capstone (VLA)',
            link: {
              type: 'generated-index',
              description: 'Weeks 11-13: Vision-Language-Action systems, advanced VLA implementation, and capstone project'
            },
            items: [
              'module-4-vla-capstone/week-11',
              'module-4-vla-capstone/week-12',
              'module-4-vla-capstone/week-13'
            ],
          },
        ],
      },
    ],
  };
}

module.exports = generateSidebars();